### ISSUE TITLE
Authorization fail message

### ISSUE THREAD

**Issue by stevenbarragan** [allolex/nacre-old#10]
You definitely need a way to tell the user that the authentication failed, right now it fails, there is no way to know it, and you constantly get pretty weird errors.

**Comment by allolex** [comment]
Yeah, I'm currently working on another version of this gem. In order to develop it quickly, I'm using some private data from a client, which means I can't release it until that is cleaned up. I might be able to do that after the 5th.

The new code isn't as feature-complete, either, but it's better code. I'm currently working on it.

Looking at this code base, it's pretty embarrassing all the things I didn't do, but that particular problem is fixed in the current version, not that it helps you right now.

Just a note: when you attempt to get data from the API and you aren't authenticated, it gives you a 200 with an error like this:

``` json
{
  "response": "Not authenticated. You must provide a valid authentication token."
}
```

Not cool. It really should be like the other errors.

``` json
{
  "errors": [
    {
      "code": "GWYB-006",
      "message": "Unable to authenticate example_user_id"
    }
  ]
}
```

**Comment by stevenbarragan** [comment]
Nice, if you open it, I could help you

**Comment by allolex** [comment]
Yeah, that's definitely what I was thinking. Can you hold on for another 8 days?

**Comment by stevenbarragan** [comment]
I'll be working on this version, we could see if we could merge the changes later.
